# Generated by Django 4.1 on 2024-03-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name0', models.CharField(max_length=255)),
                ('weight', models.FloatField(blank=True, db_column='Weight', null=True)),
                ('au', models.FloatField(blank=True, db_column='Au', null=True)),
                ('ag', models.FloatField(blank=True, db_column='Ag', null=True)),
                ('sio2', models.FloatField(blank=True, db_column='SiO2', null=True)),
                ('cao', models.FloatField(blank=True, db_column='CaO', null=True)),
                ('s', models.FloatField(blank=True, db_column='S', null=True)),
                ('fe', models.FloatField(blank=True, db_column='Fe', null=True)),
                ('cu', models.FloatField(blank=True, db_column='Cu', null=True)),
                ('al2o3', models.FloatField(blank=True, db_column='Al2O3', null=True)),
                ('as0', models.FloatField(blank=True, db_column='As0', null=True)),
            ],
            options={
                'db_table': 'materials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materialsjobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'MaterialsJobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Slag',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sio2', models.FloatField(blank=True, db_column='SiO2', null=True)),
                ('cao', models.FloatField(blank=True, db_column='CaO', null=True)),
                ('al2o3', models.FloatField(blank=True, db_column='Al2O3', null=True)),
                ('feo', models.FloatField(blank=True, db_column='FeO', null=True)),
                ('weight', models.FloatField(blank=True, db_column='Weight', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Slag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stein',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('gold', models.FloatField(blank=True, db_column='Gold', null=True)),
                ('silver', models.FloatField(blank=True, db_column='Silver', null=True)),
                ('weight', models.FloatField(blank=True, db_column='Weight', null=True)),
                ('copper', models.FloatField(blank=True, db_column='Copper', null=True)),
                ('iron', models.FloatField(blank=True, db_column='Iron', null=True)),
                ('sulfur', models.FloatField(blank=True, db_column='Sulfur', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Stein',
                'managed': False,
            },
        ),
    ]
