# Generated by Django 4.1 on 2024-04-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_metalextractiondata_metalleachresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ore_mass', models.FloatField()),
                ('metal_content', models.FloatField()),
            ],
            options={
                'db_table': 'Metal',
                'managed': False,
            },
        ),
    ]
